Wrap this in retries

diff --git a/.tekton/python-app-pull-request.yaml b/.tekton/python-app-pull-request.yaml
--- a/.tekton/python-app-pull-request.yaml
+++ b/.tekton/python-app-pull-request.yaml
@@ -412,6 +412,27 @@ spec:
                   TEST_OUTPUT=
                   parse_test_output $(context.task.name) sarif sast_snyk_check_out.json  || true
 
+                  upload_with_retry() {
+
+                    status=-1
+                    max_try=8
+                    wait_sec=2
+
+                    for run in $(seq 1 $max_try); do
+                      status=0
+                      oras push --no-tty --registry-config "$HOME/.docker/config.json" "$@"
+                      status=$?
+                      if [ "$status" -eq 0 ]; then
+                        break
+                      fi
+                      sleep $wait_sec
+                    done
+                    if [ "$status" -ne 0 ]; then
+                      echo "Failed to upload $@ after ${max_try} tries" >&2
+                      cat err >&2
+                    fi
+                  }
+
                   UPLOAD_FILE=sast_snyk_check_out.json
                   OCI_SUBJECT=$IMAGE_URL
 
@@ -422,21 +443,7 @@ spec:
                   REPO="${REPO[0]}"
                   DIGEST=$(echo "${IMAGE_DIGEST}" | tr : -)
 
-                  echo "---"
-                  ls $HOME
-                  echo "---"
-                  find $HOME
-                  echo "---"
-                  cat $HOME/.docker/config.json | jq '.auths | keys'
-                  echo "---"
-                  cat $HOME/.docker/config.json
-                  echo "---"
-
-                  echo "${REPO}:${DIGEST}.${SUFFIX}"
-                  echo "${UPLOAD_FILE}:${MEDIA_TYPE}"
-                  echo "---"
-
-                  oras push --no-tty --registry-config "$HOME/.docker/config.json" "${REPO}:${DIGEST}.${SUFFIX}" "${UPLOAD_FILE}:${MEDIA_TYPE}"
+                  upload_with_retry "${REPO}:${DIGEST}.${SUFFIX}" "${UPLOAD_FILE}:${MEDIA_TYPE}"
 
                 # When the test is skipped, the "SNYK_EXIT_CODE" is 3 and it can also be 3 in some other situation
                 elif [[ "$test_not_skipped" -eq 0 ]]; then
